Preprocessing of review data

In [2]:
!pip install kagglehub

Requirement already satisfied: kagglehub in C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages (0.3.4)
Requirement already satisfied: packaging in C:\Users\William-A\AppData\Roaming\Python\Python312\site-packages (from kagglehub) (26.2)
Requirement already satisfied: requests in C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages (from kagglehub) (2.34.2)
Requirement already satisfied: tqdm in C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages (from requests->kagglehub) (3.17)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages (from requests->kagglehub) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages (from requests->kagglehub) (2026.5.20)
Requirement already satisfied: colorama in C:\Users\William-A\AppData\Roaming\Python\Python312\site-packages (from tqdm->kagglehub) (0.4.6)

In [3]:
import pandas as pd
import kagglehub
import os
import numpy as np

C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
# fetch data from Kaggle if not already there
path = kagglehub.dataset_download("marlesson/myanimelist-dataset-animes-profiles-reviews")

Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 1.0.0)

In [6]:
df = pd.read_csv(os.path.join(path, 'reviews.csv'))

In [7]:
df.columns

Index(['uid', 'profile', 'anime_uid', 'text', 'score', 'scores', 'link'], dtype='str')

In [8]:
#do we remove also uid?
#Note: I added profile, because uid is not the id of the user but of the review itself
df = df[['uid', 'profile', 'anime_uid', 'score']].drop_duplicates()

In [9]:
df.groupby(['profile', 'anime_uid']).value_counts()

profile           anime_uid  uid     score
-----noname-----  2025       221727  4        1
                  18441      210287  2        1
---SnowFlake---   1535       208633  6        1
---was-----       10110      79296   8        1
--EYEPATCH--      35839      274580  10       1
                                             ..
zzz-anime         38938      309451  8        1
zzzb              28761      272281  8        1
zzzjynne          6675       322680  7        1
                  18679      322740  8        1
zzzzzzzz          9756       36814   10       1
Name: count, Length: 130519, dtype: int64

In [11]:
df = df.rename(columns={"anime_uid": "anime_id"})
df

           uid          profile  anime_id  score
0       255938   DesolatePsyche     34096      8
1       259117        baekbeans     34599     10
2       253664             skrn     28891      7
3         8254     edgewalker00      2904      9
4       291149  aManOfCulture99      4181     10
...        ...              ...       ...    ...
182629  146535        iHitokage      2593     10
182631   13126           Onegai      2593      7
182633  127899         Murasa22      2593     10
182636  286852  srry4apologizng      2593      9
182637  193145        bellellis      2593     10

[130519 rows x 4 columns]

In [13]:
df = df[["profile", "anime_id","score"]]
df

                profile  anime_id  score
0        DesolatePsyche     34096      8
1             baekbeans     34599     10
2                  skrn     28891      7
3          edgewalker00      2904      9
4       aManOfCulture99      4181     10
...                 ...       ...    ...
182629        iHitokage      2593     10
182631           Onegai      2593      7
182633         Murasa22      2593     10
182636  srry4apologizng      2593      9
182637        bellellis      2593     10

[130519 rows x 3 columns]

In [15]:
df.to_csv("../data/preprocessed/reviews.csv")