Preprocessing of anime data

In [6]:
# only launch if kagglehub is not yet installed
!pip install kagglehub

Requirement already satisfied: kagglehub in C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages (0.3.4)
Requirement already satisfied: packaging in C:\Users\William-A\AppData\Roaming\Python\Python312\site-packages (from kagglehub) (26.2)
Requirement already satisfied: requests in C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages (from kagglehub) (2.34.2)
Requirement already satisfied: tqdm in C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages (from requests->kagglehub) (3.17)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages (from requests->kagglehub) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\William-A\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages (from requests->kagglehub) (2026.5.20)
Requirement already satisfied: colorama in C:\Users\William-A\AppData\Roaming\Python\Python312\site-packages (from tqdm->kagglehub) (0.4.6)

In [7]:
import pandas as pd
import kagglehub
import os
import numpy as np

In [8]:
path = kagglehub.dataset_download("marlesson/myanimelist-dataset-animes-profiles-reviews")

Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 1.0.0)

In [9]:
df = pd.read_csv(os.path.join(path, 'animes.csv'))

In [10]:
df.rename(columns={'uid': 'anime_id'}, inplace=True)

In [11]:
df.columns

Index(['anime_id', 'title', 'synopsis', 'genre', 'aired', 'episodes',
       'members', 'popularity', 'ranked', 'score', 'img_url', 'link'],
      dtype='str')

In [15]:
df = df[['anime_id', 'genre']].drop_duplicates()
df.groupby(['anime_id', 'genre']).value_counts()
df

       anime_id                                              genre
0         28891  ['Comedy', 'Sports', 'Drama', 'School', 'Shoun...
1         23273  ['Drama', 'Music', 'Romance', 'School', 'Shoun...
2         34599  ['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...
3          5114  ['Action', 'Military', 'Adventure', 'Comedy', ...
4         31758   ['Action', 'Mystery', 'Supernatural', 'Vampire']
...         ...                                                ...
19002     10075  ['Action', 'Comedy', 'Super Power', 'Martial A...
19003     35828        ['Slice of Life', 'Comedy', 'Supernatural']
19004     10378             ['Slice of Life', 'Comedy', 'Shounen']
19005     33082                                         ['Action']
19006     16934  ['Comedy', 'Drama', 'Romance', 'School', 'Slic...

[16216 rows x 2 columns]

In [17]:


df['genre'] = df['genre'].str.replace(r"[\[\]']", '', regex=True).str.lower().str.strip()

# anime_clean['genres_array'] = anime_clean['genre'].str.split(r',\s*')

df = df.dropna(subset=['genre'])
df

       anime_id                                              genre
0         28891             comedy, sports, drama, school, shounen
1         23273             drama, music, romance, school, shounen
2         34599         sci-fi, adventure, mystery, drama, fantasy
3          5114  action, military, adventure, comedy, drama, ma...
4         31758             action, mystery, supernatural, vampire
...         ...                                                ...
19002     10075  action, comedy, super power, martial arts, sho...
19003     35828                slice of life, comedy, supernatural
19004     10378                     slice of life, comedy, shounen
19005     33082                                             action
19006     16934      comedy, drama, romance, school, slice of life

[16216 rows x 2 columns]

In [18]:
df.to_csv("../data/preprocessed/animes.csv")